config/routes.rb
Rails.application.routes.draw do
  get 'static_pages1/home'
  resources:logins
  resources:registers
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'registers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/register.rb
class Register < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def hello
    render html: "hello, world!"
 end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:username, :password)
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:username, :password, :confirmpassword, :email)
    end
end

app/controllers/static_pages1_controller.rb
class StaticPages1Controller < ApplicationController
  def home
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/.rb
module LoginsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/static_pages1_helper.rb
module StaticPages1Helper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/_form.html.haml
= form_for @login do |f|
  - if @login.errors.any?
    #error_explanation
      %h2= "#{pluralize(@login.errors.count, "error")} prohibited this login from being saved:"
      %ul
        - @login.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Login'

app/views/logins/edit.html.haml
%h1 Editing login

= render 'form'

= link_to 'Show', @login
\|
= link_to 'Back', logins_path

app/views/logins/index.html.haml
%h1 Listing logins

%table
  %thead
    %tr
      %th Username
      %th Password
      %th
      %th
      %th

  %tbody
    - @logins.each do |login|
      %tr
        %td= login.username
        %td= login.password
        %td= link_to 'Show', login
        %td= link_to 'Edit', edit_login_path(login)
        %td= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Login', new_login_path

app/views/logins/new.html.haml
%h1 New login

= render 'form'

= link_to 'Back', logins_path

app/views/logins/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @login.username
%p
  %b Password:
  = @login.password

= link_to 'Edit', edit_login_path(@login)
\|
= link_to 'Back', logins_path

app/views/registers/_form.html.haml
= form_for @register do |f|
  - if @register.errors.any?
    #error_explanation
      %h2= "#{pluralize(@register.errors.count, "error")} prohibited this register from being saved:"
      %ul
        - @register.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :confirmpassword
    = f.text_field :confirmpassword
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Create'

app/views/registers/edit.html.haml
%h1 Editing register

= render 'form'

= link_to 'Show', @register
\|
= link_to 'Back', registers_path

app/views/registers/index.html.haml
%h1 Listing registers

%table
  %thead
    %tr
      %th Username
      %th Password
      %th Confirmpassword
      %th Email
      %th
      %th
      %th

  %tbody
    - @registers.each do |register|
      %tr
        %td= register.username
        %td= register.password
        %td= register.confirmpassword
        %td= register.email
        %td= link_to 'Show', register
        %td= link_to 'Edit', edit_register_path(register)
        %td= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Register', new_register_path

app/views/registers/new.html.haml
%h1 New register

= render 'form'

= link_to 'Back', registers_path

app/views/registers/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @register.username
%p
  %b Password:
  = @register.password
%p
  %b Confirmpassword:
  = @register.confirmpassword
%p
  %b Email:
  = @register.email

= link_to 'Edit', edit_register_path(@register)
\|
= link_to 'Back', registers_path

app/views/static_pages/about.html.erb
<h2>Team Member</h2>
<ol>

    <li>นางสาวพรนภัส  ทศนุต รหัสนักศึกษา 6010613468</li>
    <li>นางสาวนภัสสร พิสุทธิ์ธาราชัย รหัสนักศึกษา 6010613476</li>
    <li>นางสาวกณวรรธน์ เหลืองอรุณโรจน์ รหัสนักศึกษา 6010613583</li>
    <li>นายสมปราชญ์ เนตรสมสว่าง รหัสนักศึกษา 6010680210</li>


</ol>
<a href="https://drive.google.com/open?id=1bJKhbyh9y745xlAGuyXSXnhTiUjm1Kmv" target="_blank">Perposal</a><br>
<a href="https://drive.google.com/open?id=1kz56psE02Fz6I158eG93wC9lYKDttEmb" target="_blank">User Story</a><br>
<a href="https://gitlab.com/CN340EXCUEME/app.git" target="_blank">Links to git repository</a><br>
<a href=" https://www.pivotaltracker.com/projects/2405586" target="_blank">Links to pivotal tracker</a><br>